// alcoh 前端插件系统协议。
//
// 传输层为 NDJSON JSON-RPC 2.0（每行一个 JSON 对象，经 stdio 双向传输）；
// 每个方法的 params / result 均为 {"data": "<base64(protobuf)>"} 的单字段对象，
// data 中按本 schema 编码对应消息。任何语言的插件只要能用 protoc 生成本
// schema 的代码，即可与 alcoh 对接。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/plugin/v1/plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptResult_Action int32

const (
	PromptResult_ACTION_UNSPECIFIED PromptResult_Action = 0
	// 原样发送。
	PromptResult_ACTION_ALLOW PromptResult_Action = 1
	// 以 rewritten 替换后发送。
	PromptResult_ACTION_REWRITE PromptResult_Action = 2
	// 拦截发送，reason 展示给用户。
	PromptResult_ACTION_BLOCK PromptResult_Action = 3
)

// Enum value maps for PromptResult_Action.
var (
	PromptResult_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ALLOW",
		2: "ACTION_REWRITE",
		3: "ACTION_BLOCK",
	}
	PromptResult_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ALLOW":       1,
		"ACTION_REWRITE":     2,
		"ACTION_BLOCK":       3,
	}
)

func (x PromptResult_Action) Enum() *PromptResult_Action {
	p := new(PromptResult_Action)
	*p = x
	return p
}

func (x PromptResult_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PromptResult_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PromptResult_Action) Type() protoreflect.EnumType {
	return &file_proto_plugin_v1_plugin_proto_enumTypes[0]
}

func (x PromptResult_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PromptResult_Action.Descriptor instead.
func (PromptResult_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5, 0}
}

// InitializeRequest 是 alcoh 在插件进程启动后发出的第一条消息。
type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version 是插件协议版本，当前为 1。插件应拒绝不认识的版本。
	ProtocolVersion int32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// host_name / host_version 是宿主（alcoh）的标识与版本。
	HostName    string `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	HostVersion string `protobuf:"bytes,3,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	// cwd 是 alcoh 当前工作目录（会话默认目录）。
	Cwd           string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *InitializeRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *InitializeRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *InitializeRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

// InitializeResult 是插件对 initialize 的应答：声明自身信息、要接收的 hook
// 与注册的斜杠命令。
type InitializeResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// hooks_prompt 为 true 时，每次提交 prompt 前 alcoh 会调用 hook/prompt。
	HooksPrompt bool `protobuf:"varint,4,opt,name=hooks_prompt,json=hooksPrompt,proto3" json:"hooks_prompt,omitempty"`
	// hooks_update 为 true 时，每个 ACP 事件 alcoh 会以 hook/update 通知插件。
	HooksUpdate bool `protobuf:"varint,5,opt,name=hooks_update,json=hooksUpdate,proto3" json:"hooks_update,omitempty"`
	// key_bindings 声明需要拦截的按键；未列出的按键不会产生任何 IPC。
	KeyBindings []*KeyBinding `protobuf:"bytes,6,rep,name=key_bindings,json=keyBindings,proto3" json:"key_bindings,omitempty"`
	// commands 注册到命令面板的斜杠命令（以 / 开头）。
	Commands      []*CommandInfo `protobuf:"bytes,7,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResult) Reset() {
	*x = InitializeResult{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResult) ProtoMessage() {}

func (x *InitializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResult.ProtoReflect.Descriptor instead.
func (*InitializeResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializeResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InitializeResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitializeResult) GetHooksPrompt() bool {
	if x != nil {
		return x.HooksPrompt
	}
	return false
}

func (x *InitializeResult) GetHooksUpdate() bool {
	if x != nil {
		return x.HooksUpdate
	}
	return false
}

func (x *InitializeResult) GetKeyBindings() []*KeyBinding {
	if x != nil {
		return x.KeyBindings
	}
	return nil
}

func (x *InitializeResult) GetCommands() []*CommandInfo {
	if x != nil {
		return x.Commands
	}
	return nil
}

// KeyBinding 描述一个按键绑定。type 取值与 alcoh 的 input.KeyType 对应：
// "rune" | "enter" | "tab" | "backspace" | "delete" | "esc" | "up" | "down" |
// "left" | "right" | "home" | "end" | "pageup" | "pagedown" | "insert" |
// "f1".."f12"。
type KeyBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// rune 在 type == "rune" 时为 Unicode 码点。
	Rune          uint32 `protobuf:"varint,2,opt,name=rune,proto3" json:"rune,omitempty"`
	Ctrl          bool   `protobuf:"varint,3,opt,name=ctrl,proto3" json:"ctrl,omitempty"`
	Alt           bool   `protobuf:"varint,4,opt,name=alt,proto3" json:"alt,omitempty"`
	Shift         bool   `protobuf:"varint,5,opt,name=shift,proto3" json:"shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBinding) Reset() {
	*x = KeyBinding{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBinding) ProtoMessage() {}

func (x *KeyBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBinding.ProtoReflect.Descriptor instead.
func (*KeyBinding) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *KeyBinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KeyBinding) GetRune() uint32 {
	if x != nil {
		return x.Rune
	}
	return 0
}

func (x *KeyBinding) GetCtrl() bool {
	if x != nil {
		return x.Ctrl
	}
	return false
}

func (x *KeyBinding) GetAlt() bool {
	if x != nil {
		return x.Alt
	}
	return false
}

func (x *KeyBinding) GetShift() bool {
	if x != nil {
		return x.Shift
	}
	return false
}

// CommandInfo 是插件注册的斜杠命令。
type CommandInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 以 / 开头，如 "/hello"。
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// args_hint 展示在命令面板，如 "[name]"。
	ArgsHint      string `protobuf:"bytes,3,opt,name=args_hint,json=argsHint,proto3" json:"args_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CommandInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandInfo) GetArgsHint() string {
	if x != nil {
		return x.ArgsHint
	}
	return ""
}

// PromptRequest 携带即将提交给 ACP agent 的 prompt。
type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PromptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// PromptResult 是插件的裁决：放行 / 改写 / 拦截。
type PromptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        PromptResult_Action    `protobuf:"varint,1,opt,name=action,proto3,enum=alcoh.plugin.v1.PromptResult_Action" json:"action,omitempty"`
	Rewritten     string                 `protobuf:"bytes,2,opt,name=rewritten,proto3" json:"rewritten,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResult) Reset() {
	*x = PromptResult{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResult) ProtoMessage() {}

func (x *PromptResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResult.ProtoReflect.Descriptor instead.
func (*PromptResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PromptResult) GetAction() PromptResult_Action {
	if x != nil {
		return x.Action
	}
	return PromptResult_ACTION_UNSPECIFIED
}

func (x *PromptResult) GetRewritten() string {
	if x != nil {
		return x.Rewritten
	}
	return ""
}

func (x *PromptResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// KeyRequest 携带一次按键及其上下文。仅当该键命中插件声明的 key_bindings
// 时才会被调用。
type KeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 与 KeyBinding.type 同义。
	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Rune  uint32 `protobuf:"varint,2,opt,name=rune,proto3" json:"rune,omitempty"`
	Ctrl  bool   `protobuf:"varint,3,opt,name=ctrl,proto3" json:"ctrl,omitempty"`
	Alt   bool   `protobuf:"varint,4,opt,name=alt,proto3" json:"alt,omitempty"`
	Shift bool   `protobuf:"varint,5,opt,name=shift,proto3" json:"shift,omitempty"`
	// view 为 "home" | "session"。
	View string `protobuf:"bytes,6,opt,name=view,proto3" json:"view,omitempty"`
	// modal 为当前弹窗："none" | "settings" | "help" | "effort" | "model" |
	// "server" | "permission" | "elicitation" | "exit_confirm" | "onboarding" |
	// "connect"。非 "none" 时通常不拦截。
	Modal string `protobuf:"bytes,7,opt,name=modal,proto3" json:"modal,omitempty"`
	// input_empty / input 是输入框状态。
	InputEmpty    bool   `protobuf:"varint,8,opt,name=input_empty,json=inputEmpty,proto3" json:"input_empty,omitempty"`
	Input         string `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *KeyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KeyRequest) GetRune() uint32 {
	if x != nil {
		return x.Rune
	}
	return 0
}

func (x *KeyRequest) GetCtrl() bool {
	if x != nil {
		return x.Ctrl
	}
	return false
}

func (x *KeyRequest) GetAlt() bool {
	if x != nil {
		return x.Alt
	}
	return false
}

func (x *KeyRequest) GetShift() bool {
	if x != nil {
		return x.Shift
	}
	return false
}

func (x *KeyRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *KeyRequest) GetModal() string {
	if x != nil {
		return x.Modal
	}
	return ""
}

func (x *KeyRequest) GetInputEmpty() bool {
	if x != nil {
		return x.InputEmpty
	}
	return false
}

func (x *KeyRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// KeyResult 返回该按键是否已被插件消费（handled=true 时 alcoh 不再处理）。
type KeyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResult) Reset() {
	*x = KeyResult{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResult) ProtoMessage() {}

func (x *KeyResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResult.ProtoReflect.Descriptor instead.
func (*KeyResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *KeyResult) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

// UpdateRequest 是 ACP 事件流中一个事件的只读快照。作为 notification
// 发送，插件不应回复。
type UpdateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// method 是事件判别符，如 "message_chunk"、"state_update"、"usage_update"、
	// "tool_call_update" 等（与 alcoh internal/acp 事件类型一一对应）。
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// payload 是事件的原始 JSON（尽力而为；无法 JSON 化的内部事件为空）。
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UpdateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CommandRequest 是用户执行插件斜杠命令时发送。
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command 是完整命令 token，如 "/hello"。
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// args 是命令名之后剩余的输入。
	Args          string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// handled=false 时该命令视为未执行。
	Handled       bool `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *CommandResult) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

// ShutdownNotice 表示 alcoh 即将退出；插件应尽快清理并退出。
type ShutdownNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownNotice) Reset() {
	*x = ShutdownNotice{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownNotice) ProtoMessage() {}

func (x *ShutdownNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownNotice.ProtoReflect.Descriptor instead.
func (*ShutdownNotice) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

// NotifyRequest 在 TUI 底部展示一条提示。
type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind 为 "info" | "success" | "error"。
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NotifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// StatusRequest 设置状态栏左侧的插件状态文本；text 为空串时清除。
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *StatusRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// LogRequest 输出一条日志（写入 alcoh stderr，不污染 TUI）。
type LogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level 为 "debug" | "info" | "warn" | "error"。
	Level         string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Empty 是插件 → Host 请求的通用空 result。
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\x0falcoh.plugin.v1\"\x90\x01\n" +
	"\x11InitializeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12!\n" +
	"\fhost_version\x18\x03 \x01(\tR\vhostVersion\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\"\xa2\x02\n" +
	"\x10InitializeResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\fhooks_prompt\x18\x04 \x01(\bR\vhooksPrompt\x12!\n" +
	"\fhooks_update\x18\x05 \x01(\bR\vhooksUpdate\x12>\n" +
	"\fkey_bindings\x18\x06 \x03(\v2\x1b.alcoh.plugin.v1.KeyBindingR\vkeyBindings\x128\n" +
	"\bcommands\x18\a \x03(\v2\x1c.alcoh.plugin.v1.CommandInfoR\bcommands\"p\n" +
	"\n" +
	"KeyBinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04rune\x18\x02 \x01(\rR\x04rune\x12\x12\n" +
	"\x04ctrl\x18\x03 \x01(\bR\x04ctrl\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\bR\x03alt\x12\x14\n" +
	"\x05shift\x18\x05 \x01(\bR\x05shift\"`\n" +
	"\vCommandInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\targs_hint\x18\x03 \x01(\tR\bargsHint\"F\n" +
	"\rPromptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"\xdc\x01\n" +
	"\fPromptResult\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.alcoh.plugin.v1.PromptResult.ActionR\x06action\x12\x1c\n" +
	"\trewritten\x18\x02 \x01(\tR\trewritten\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"X\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x12\n" +
	"\x0eACTION_REWRITE\x10\x02\x12\x10\n" +
	"\fACTION_BLOCK\x10\x03\"\xd1\x01\n" +
	"\n" +
	"KeyRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04rune\x18\x02 \x01(\rR\x04rune\x12\x12\n" +
	"\x04ctrl\x18\x03 \x01(\bR\x04ctrl\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\bR\x03alt\x12\x14\n" +
	"\x05shift\x18\x05 \x01(\bR\x05shift\x12\x12\n" +
	"\x04view\x18\x06 \x01(\tR\x04view\x12\x14\n" +
	"\x05modal\x18\a \x01(\tR\x05modal\x12\x1f\n" +
	"\vinput_empty\x18\b \x01(\bR\n" +
	"inputEmpty\x12\x14\n" +
	"\x05input\x18\t \x01(\tR\x05input\"%\n" +
	"\tKeyResult\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\"`\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"]\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\")\n" +
	"\rCommandResult\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\"\x10\n" +
	"\x0eShutdownNotice\"7\n" +
	"\rNotifyRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"#\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"6\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\a\n" +
	"\x05EmptyB+Z)github.com/cxykevin/alcoh/pb/plugin/v1;v1b\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(PromptResult_Action)(0),  // 0: alcoh.plugin.v1.PromptResult.Action
	(*InitializeRequest)(nil), // 1: alcoh.plugin.v1.InitializeRequest
	(*InitializeResult)(nil),  // 2: alcoh.plugin.v1.InitializeResult
	(*KeyBinding)(nil),        // 3: alcoh.plugin.v1.KeyBinding
	(*CommandInfo)(nil),       // 4: alcoh.plugin.v1.CommandInfo
	(*PromptRequest)(nil),     // 5: alcoh.plugin.v1.PromptRequest
	(*PromptResult)(nil),      // 6: alcoh.plugin.v1.PromptResult
	(*KeyRequest)(nil),        // 7: alcoh.plugin.v1.KeyRequest
	(*KeyResult)(nil),         // 8: alcoh.plugin.v1.KeyResult
	(*UpdateRequest)(nil),     // 9: alcoh.plugin.v1.UpdateRequest
	(*CommandRequest)(nil),    // 10: alcoh.plugin.v1.CommandRequest
	(*CommandResult)(nil),     // 11: alcoh.plugin.v1.CommandResult
	(*ShutdownNotice)(nil),    // 12: alcoh.plugin.v1.ShutdownNotice
	(*NotifyRequest)(nil),     // 13: alcoh.plugin.v1.NotifyRequest
	(*StatusRequest)(nil),     // 14: alcoh.plugin.v1.StatusRequest
	(*LogRequest)(nil),        // 15: alcoh.plugin.v1.LogRequest
	(*Empty)(nil),             // 16: alcoh.plugin.v1.Empty
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	3, // 0: alcoh.plugin.v1.InitializeResult.key_bindings:type_name -> alcoh.plugin.v1.KeyBinding
	4, // 1: alcoh.plugin.v1.InitializeResult.commands:type_name -> alcoh.plugin.v1.CommandInfo
	0, // 2: alcoh.plugin.v1.PromptResult.action:type_name -> alcoh.plugin.v1.PromptResult.Action
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
