//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

//go:generate go run gen.go

const template = `// Code generated by go generate; DO NOT EDIT.
package product

// CommitID 提交ID
const CommitID = "{commitID}"

// BuildTime 构建时间
const BuildTime uint64 = {buildTime}

// BuildNote 构建备注
const BuildNote = "{note}"

// Version 版本号
const Version = "{version_tag}"

// VersionID 版本ID
const VersionID = {version_id}
`

func main() {
	const tgt = "build.go" // 生成的文件名

	commitID := "unknown"
	if out, err := exec.Command("git", "rev-parse", "HEAD").Output(); err == nil {
		commitID = strings.TrimSpace(string(out))
	}

	buildTime := time.Now().Unix()

	note := os.Getenv("ALCOH_BUILD_NOTE")

	// 获取最新的 tag（即使当前提交不在 tag 上）；无 git/无 tag 时回退 v0.0.0。
	versionTag := "v0.0.0"
	if out, err := exec.Command("git", "describe", "--tags", "--abbrev=0").Output(); err == nil {
		versionTag = strings.TrimSpace(string(out))
	}

	// 计算该 tag 是第几个 tag（按版本排序升序，1-based）。
	versionID := 0
	if tagListOut, err := exec.Command("git", "tag", "--sort=v:refname").Output(); err == nil {
		tagList := strings.Split(strings.TrimSpace(string(tagListOut)), "\n")
		for i, t := range tagList {
			if t == versionTag {
				versionID = i + 1 // 1-based
				break
			}
		}
	}
	versionTag = strings.TrimPrefix(versionTag, "v")

	// 转义 BUILD_NOTE 中的特殊字符，避免含引号/换行/反斜杠时生成不可编译的字符串字面量
	note = escapeStringLiteral(note)

	rendered := template
	rendered = strings.ReplaceAll(rendered, "{commitID}", commitID)
	rendered = strings.ReplaceAll(rendered, "{buildTime}", fmt.Sprintf("%d", buildTime))
	rendered = strings.ReplaceAll(rendered, "{note}", note)
	rendered = strings.ReplaceAll(rendered, "{version_tag}", versionTag)
	rendered = strings.ReplaceAll(rendered, "{version_id}", fmt.Sprintf("%d", versionID))

	// gofmt 一下
	src, err := format.Source([]byte(rendered))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(tgt, src, 0644); err != nil {
		log.Fatal(err)
	}
	commitShort := commitID
	if len(commitShort) > 8 {
		commitShort = commitID[:8]
	}
	fmt.Printf("generated %s version=%s versionID=%d commit=%s\n", tgt, versionTag, versionID, commitShort)
}

// escapeStringLiteral 将字符串转义为合法的 Go 字符串字面量内容
func escapeStringLiteral(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\r", `\r`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return s
}
